### ISSUE TITLE
Same hash for the object every time I run the program

### ISSUE THREAD

**Issue by dzGeekyGirl** [udacity/nd1309_hashing#5]
Hi,
In the quiz when they asked 
Select the Cause
What is happening with the hash of the dataObject variable every time we run the program?
I understand that the right answers should be The hash changes every time I run the program. since the time parameter in the object change every time we run the programm but it's not what I have. Everytime I run the programm I have the same Hash for the object.
this is my code
`/**
 * Step 1: Verify 'crypto-js' module is installed for your project
 * After verifying it is installed, move on to Step 2. No code needs to be written here.
 */

/**
 * Step 2: Import from crypto-js module the sha265 library
 */

// Write your code here

/**
 * Variables: Do not change variable values to be able to answer the quiz
 */
const SHA256 = require("crypto-js/sha256");
const data1 = "Blockchain Rock!";
const dataObject = {
	id: 1,
  	body: "With Object Works too",
  	time: new Date().getTime().toString().slice(0,-3)
};

/**
 * Step 3: Add code to the `generate hash function
 * Function that generate the SHA256 Hash
 * @param {*} obj 
 */

function generateHash(obj) {
	// Write your code here
	return SHA256(obj);
}

console.log(`SHA256 Hash: ${generateHash(data1)}`);
console.log("************************************");
console.log(`SHA256 Hash: ${generateHash(dataObject)}`);
console.log("************************************");
/**
 * Run your application using `node app.js`
 */
`

**Comment by orochiwolf** [comment]
Use the JavaScript function JSON.stringify() to convert it into a string. var myJSON = JSON.stringify(obj); The result will be a string following the JSON notation.
This is also the way that object are treated in the documentation of the crypto-js
https://www.npmjs.com/package/crypto-js#usage

**Comment by dzGeekyGirl** [comment]
> Use the JavaScript function JSON.stringify() to convert it into a string. var myJSON = JSON.stringify(obj); The result will be a string following the JSON notation.
> This is also the way that object are treated in the documentation of the crypto-js
> https://www.npmjs.com/package/crypto-js#usage

thank you. It actually worked.
